# Generated by Django 5.0.6 on 2024-07-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organization_name',
        ),
    ]
