# Generated by Django 5.0.6 on 2024-07-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_organization_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='country',
            new_name='username',
        ),
    ]
