# Generated by Django 5.0.6 on 2024-07-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_net_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(default='expense', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='transaction_type',
            field=models.CharField(default='income', max_length=20, null=True),
        ),
    ]
