# Generated by Django 5.0.6 on 2024-07-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_budget_end_date_alter_budget_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
