# Generated by Django 5.0.6 on 2024-08-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_budget_start_date_alter_profile_phone_number'),
        ('user', '0013_alter_budget_start_date_message'),
    ]

    operations = [
    ]
