# Generated by Django 5.0.6 on 2024-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_feedback_alter_budget_name_alter_budget_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
